config/routes.rb
ManageApp::Application.routes.draw do
  resources :password_resets

  namespace :admin do
    get "/" => "home#index"
  end

  resources :users, :only => [:new, :create, :show, :index] do
    member do 
      get :activate
    end

    resources :help, :only => [:index]

    resources :access_tokens, :path => "tokens" do
      collection do 
        get :generate
      end
    end

    resources :keys, :only => [:index, :create, :destroy]

    resources :dashboard, :only => [:index]
  end

  get "login"   => "sessions#new",      :as => :login
  get "logout"  => "sessions#destroy",  :as => :logout
  get "signup"  => "users#new",         :as => :signup

  resources :sessions

  root :to => 'home#index'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	layout "sessions"
	skip_before_filter :require_login

	def new
		@user = User.new
	end

	def create
		@user = User.find_by_email(params[:user][:email])

		if @user
			@user.deliver_reset_password_instructions!

			redirect_to login_path, :notice => "Instructions have been sent to your email."
		else
			@user = User.new
			render :action => :new
		end
	end

	def edit
 		@user = User.load_from_reset_password_token(params[:id])
    	@token = params[:id]
    	not_authenticated unless @user
	end

	def update
		@token = params[:user][:token]
		@user = User.load_from_reset_password_token(@token)
		not_authenticated unless @user
		# the next line makes the password confirmation validation work
		@user.password_confirmation = params[:user][:password_confirmation]
		# the next line clears the temporary token and updates the password
		if @user.change_password!(params[:user][:password])
		  redirect_to(login_path, :notice => 'Password was successfully updated.')
		else
		  render :action => "edit"
		 end
    end
end

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<div id="logo">
	<img src="/assets/invert-logo.png" alt="10xEngineer Labs" />
	</div>
  <div id="sessions">
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
</div>

<div id="resetbox" class="reset2">	
	<%= simple_form_for @user, :url => password_reset_path(@user), :html => { :class => 'form-vertical' } do |f| %>
		<p>Enter new password</p>
		<%= f.input :password, :label => false, :placeholder => "Password", :wrapper => :unicorn %>
		<%= f.input :password_confirmation, :label => false, :placeholder => "Confirmation", :wrapper => :unicorn %>
		<%= f.input :token, :as => :hidden, :input_html => { :value => @token } %>
		<div class="form-actions">
        	<span class="pull-left">Don't have account? <a href="/signup">Sign up</a> today. <br/></span>
            <span class="pull-right"><%= f.submit 'Change', :class => 'btn btn-inverse' %></span>
		</div>
	<% end %>
</div>

app/views/password_resets/new.html.erb
<div id="logo">
	<img src="/assets/invert-logo.png" alt="10xEngineer Labs" />
	</div>
  <div id="sessions">
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
</div>

<div id="resetbox" class="reset1">	
	<%= simple_form_for @user, :url => password_resets_path, :html => { :class => 'form-vertical' } do |f| %>
    <p>Enter your email address</p>
		<%= f.input :email, :label => false, :placeholder => "Email", :wrapper => :unicorn %>
		<div class="form-actions">
            <span class="pull-right"><%= f.submit 'Reset password!', :class => 'btn btn-inverse' %></span>
		</div>
	<% end %>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>