config/routes.rb
ManageApp::Application.routes.draw do
  resources :password_resets

  namespace :admin do
    get "/" => "home#index"
  end

  resources :users, :only => [:new, :create, :show, :index] do
    member do 
      get :activate
    end

    resources :help, :only => [:index]

    resources :access_tokens, :path => "tokens" do
      collection do 
        get :generate
      end
    end

    resources :keys, :only => [:index, :create, :destroy]

    resources :dashboard, :only => [:index]
  end

  get "login"   => "sessions#new",      :as => :login
  get "logout"  => "sessions#destroy",  :as => :logout
  get "signup"  => "users#new",         :as => :signup

  resources :sessions

  root :to => 'home#index'

end

app/models/key.rb
class Key
	include Mongoid::Document
	include Mongoid::Timestamps

	field :name, type: String

	field :fingerprint, type: String
	field :public_key, type: String

	belongs_to :user

	field :deleted_at, type: DateTime

	validates_presence_of :name
	validates_presence_of :public_key
end

app/controllers/keys_controller.rb
require 'sshkey'
require 'key'

class KeysController < ProtectedController
  def index
    begin
      @keys = Key.where(user_id: @current_user._id).to_a
    rescue Mongoid::Errors::DocumentNotFound
      @keys = []
    end

  	@key = Key.new
  end

  def create
  	@key = Key.new(params[:key])

    # check pem public key
    key = @key.public_key.strip
    if key.match /^-----BEGIN/
      pem_key = KeyConvertor.new(@key.public_key)

      @key.public_key = pem_key.ssh_public_key
    end

    parts = @key.public_key.split(' ')
    _key = parts[0..1].join(' ')

  	@key.fingerprint = SSHKey.fingerprint(_key)
  	@key.user_id = @current_user._id

  	if SSHKey.valid_ssh_public_key?(@key.public_key) && @key.save  		
      $customerio.delay.track(@current_user, "key_created")
  		redirect_to user_keys_path(@current_user), :notice => "New SSH Key added!"  		
  	else
      begin
        @keys = Key.where(user_id: @current_user._id).to_a
      rescue Mongoid::Errors::DocumentNotFound
        @keys = []
      end

  		redirect_to user_keys_path(@current_user), :notice => "Invalid SSH Key"      
  	end
  end

  def destroy
  	@key = Key.find_by(name: params[:id], user_id: params[:user_id])
    @key.destroy

    $customerio.delay.track(@current_user, "key_destroyed")

    logger.warn "#{Time.new.utc} key=#{@key._id} removed by user=#{@current_user._id}"

  	redirect_to user_keys_path(@current_user), :notice => "SSH Key removed!"
  end
end

app/views/keys/index.html.erb
<% content_for :content_header do %>
<h1>SSH Keys</h1>
<% end %>

<% if @keys.empty? %>
	<div class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert">×</button>
	  	 Use name 'default' for you primary public key.
	</div>
<% end %>

<% if @keys.empty? %>
<% else %>
<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-content nopadding">
			<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Fingerprint</th>
					<th>Created</th>
					<th>&nbsp;</th>
				</tr>
			</thead>	
			<tbody>
				<% @keys.each do |key| %>
				<tr>
					<td><%= key.name %></td>
					<td class="fingerprint"><%= key.fingerprint %></td>
					<td><%= key.created_at %></td>
					<td><%= link_to 'Delete', user_key_path(@current_user, key.name), :method => :delete, :confirm => 'Are you sure?' %></td>
				</tr>
				<% end %>
			</tbody>
			</table>
		</div>
	</div>
</div>
<% end %>

<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>									
				</span>
				<h5>Add new SSH Key</h5>
			</div>
			<div class="widget-content nopadding">
				<%= simple_form_for @key, :url => user_keys_path(@current_user), :html => { :class => 'form-horizontal' } do |f| %>
					<%= f.input :name, :placeholder => 'default' %>
					<%= f.input :public_key, :as => :text %>
					<div class="form-actions">
						<%= f.submit 'Add key', :class => "btn btn-primary" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>