config/routes.rb
ManageApp::Application.routes.draw do
  resources :password_resets

  namespace :admin do
    get "/" => "home#index"
  end

  resources :users, :only => [:new, :create, :show, :index] do
    member do 
      get :activate
    end

    resources :help, :only => [:index]

    resources :access_tokens, :path => "tokens" do
      collection do 
        get :generate
      end
    end

    resources :keys, :only => [:index, :create, :destroy]

    resources :dashboard, :only => [:index]
  end

  get "login"   => "sessions#new",      :as => :login
  get "logout"  => "sessions#destroy",  :as => :logout
  get "signup"  => "users#new",         :as => :signup

  resources :sessions

  root :to => 'home#index'

end

app/models/access_token.rb
def rand_hexstring(length=8)
		((0..length).map{rand(256).chr}*"").unpack("H*")[0][0,length]
end

class AccessToken
	include Mongoid::Document
	include Mongoid::Timestamps

	belongs_to :user

	field :alias, type: String

	field :auth_token, type: String
	field :auth_secret, type: String

	field :deleted_at, type: Date, default: nil

	def self.generate(user)
		current_token = AccessToken.where(user: user._id).first

		token = AccessToken.new(
			:user => user, 
			:alias => "default",
			:auth_token => rand_hexstring(28),
			:auth_secret => rand_hexstring(48)
			)

		if token.save
			current_token.destroy if current_token
		end
	end
end

app/controllers/access_tokens_controller.rb
class AccessTokensController < ProtectedController
	def index
		@tokens = current_user.access_tokens
	end

	def generate
		AccessToken.generate(@current_user)

		redirect_to user_access_tokens_path(@current_user), :notice => "Default key updated. Please, make sure to update clients."
	end

private
	def rand_hexstring(length=8)
  		((0..length).map{rand(256).chr}*"").unpack("H*")[0][0,length]
	end
end

app/views/access_tokens/index.html.erb
<% content_for :content_header do %>
<h1>API Tokens</h1>
<% end %>

<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-content nopadding">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Alias</th>
						<th>Token</th>
						<th>Secret</th>
					</tr>
				</thead>	
				<tbody>
					<% @tokens.each do |token| %>
					<tr>
						<td><%= token.alias %></td>
						<td><%= token.auth_token %></td>
						<td><%= token.auth_secret %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<%= link_to "Generate new", generate_user_access_tokens_path(@current_user), :class => "btn btn-info" %>