config/routes.rb
ManageApp::Application.routes.draw do
  resources :password_resets

  namespace :admin do
    get "/" => "home#index"
  end

  resources :users, :only => [:new, :create, :show, :index] do
    member do 
      get :activate
    end

    resources :help, :only => [:index]

    resources :access_tokens, :path => "tokens" do
      collection do 
        get :generate
      end
    end

    resources :keys, :only => [:index, :create, :destroy]

    resources :dashboard, :only => [:index]
  end

  get "login"   => "sessions#new",      :as => :login
  get "logout"  => "sessions#destroy",  :as => :logout
  get "signup"  => "users#new",         :as => :signup

  resources :sessions

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ManageApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/assets/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    
    <div id="header">
      <h1><a href="/">10xEngineer Labs</a></h1>   
    </div>

    <div id="user-nav" class="navbar navbar-inverse">
            <ul class="nav btn-group">
              <% if false %>
                <li class="btn btn-inverse" ><a title="" href="#"><i class="icon icon-user"></i> <span class="text">Profile</span></a></li>
                <li class="btn btn-inverse"><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
              <% end %>
                <li class="btn btn-inverse"><a title="" href="http://help.10xengineer.me/"><i class="icon icon-question-sign"></i> <span class="text">Support</span></a></li>              
                <li class="btn btn-inverse"><a title="" href="<%= logout_path %>"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
            </ul>
        </div>

<div id="sidebar">
      <ul>
        <li <%= is_active?("users") %>><a href="<%= user_path(@current_user) %>"><i class="icon icon-user"></i> <span>Overview</span></a></li>
        <li <%= is_active?("dashboard") %>><a href="<%= user_dashboard_index_path(@current_user) %>"><i class="icon icon-home"></i> <span>Dashboard</span></a></li>
        <li <%= is_active?("help") %>><a href="<%= user_help_index_path(@current_user) %>"><i class="icon icon-info-sign"></i> <span>Getting Started</span></a></li>
        <li <%= is_active?("access_tokens") %>><a href="<%= user_access_tokens_path(current_user) %>"><i class="icon icon-upload"></i> <span>API Keys</span></a></li>
        <li <%= is_active?("keys") %>><a href="<%= user_keys_path(current_user) %>"><i class="icon icon-book"></i> <span>SSH Keys</span></a></li>
        <% if @current_user.is_admin? %>
        <li <%= is_active?("admin/home") %>><a href="<%= admin_path %>"><i class="icon icon-home"></i> <span>Admin</span></a></li>
        <% end %>
      </ul>
    </div>        

    <div id="content">
      <div id="content-header">
        <%= yield :content_header %>
      </div>

      <div class="container-fluid">
          <% flash.each do |name, msg| %>
              <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">&#215;</a>
                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
              <% end %>
            <% end %>
             <%= yield %>        
      </div>

    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :optional_scripts %>

<script type="text/javascript" src="//assets.zendesk.com/external/zenbox/v2.5/zenbox.js"></script>
<style type="text/css" media="screen, projection">
  @import url(//assets.zendesk.com/external/zenbox/v2.5/zenbox.css);
</style>
<script type="text/javascript">
  if (typeof(Zenbox) !== "undefined") {
    Zenbox.init({
      dropboxID:   "20112288",
      url:         "https://10xengineer.zendesk.com",
      tabID:       "Questions",
      tabColor:    "green",
      tabPosition: "Right",
      requester_name: "<%= @current_user.name %>",
      requester_email: "<%= @current_user.email %>"
    });
  }
</script>

<script type="text/javascript">
  var _cio = _cio || [];
  (function() {
    var a,b,c;a=function(f){return function(){_cio.push([f].
    concat(Array.prototype.slice.call(arguments,0)))}};b=["identify",
    "track"];for(c=0;c<b.length;c++){_cio[b[c]]=a(b[c])};
    var t = document.createElement('script'),
        s = document.getElementsByTagName('script')[0];
    t.async = true;
    t.id    = 'cio-tracker';
    t.setAttribute('data-site-id', 'd98bb6ac9f4e37c473b7');
    t.src = 'https://assets.customer.io/assets/track.js';
    s.parentNode.insertBefore(t, s);
  })();
</script>

<script type="text/javascript">
  _cio.identify({
    // Required attributes
    id: '<%= "#{Rails.env}_#{@current_user.id}" %>',           // Unique id for the currently signed in user in your application.
    email: '<%= @current_user.email %>', // Email of the currently signed in user.
    created_at: <%= @current_user.created_at.to_i %>,   // Timestamp in your system that represents when
  });
</script>

  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ManageApp" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "session", :media => "all" %>
    <%= favicon_link_tag '/assets/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>